### ISSUE TITLE
additional parameter callback

### ISSUE THREAD

**Issue by chriswill0w** [TaylorBriggs/stripe-lambda#7]
Do you know how I could get the the additional parameter 'callback' into the following code in index.js

`exports.handler = function(event, context, callback) {
`

I would need it because I want to integrate the AWS lambda function with the AWS API Gateway. When I add the add the additional parameter callback I get the following error when I run grunt package: 
TypeError: callback is not a function

Do you know how I can solve the issue?

**Comment by TaylorBriggs** [comment]
Looks like grunt-aws-lambda needs to be on [0.13](https://github.com/Tim-B/grunt-aws-lambda#0130)

**Comment by TaylorBriggs** [comment]
can you see if #8 fixes the issue?

**Comment by TaylorBriggs** [comment]
Closed with 0771186727cf5d6bbf15e49d67aafff6123ec3a4
