### ISSUE TITLE
grunt run and grunt package fail

### ISSUE THREAD

**Issue by staringispolite** [TaylorBriggs/stripe-lambda#9]
Looks like I can't comment or re-open this existing issue #5, but I don't see a resolution there.

Am I missing instructions on event.json setup? (file referenced in issue #5, but don't see setup instructions). If so, could someone point me in the direction of the right docs?

**Comment by TaylorBriggs** [comment]
The `event.json` file is created by the `grunt run` task, but you need to have your environment variables set in order for it to work correctly. At a minimum, your `.env` file should have these two values defined:

```
STRIPE_SECRET_KEY={YOUR_SECRET_KEY}
RECEIPT_EMAIL={YOUR_RECEIPT_EMAIL}
```

**Comment by staringispolite** [comment]
Thanks for the reply! Hm, I do have both of those set. Maybe I
misunderstood receipt_email. Is that an email address to send the owner
copies of receipts? An email template identifier for sending to buyers?
Something else?

**Comment by TaylorBriggs** [comment]
It's an email address. For the purposes of the grunt tasks, I just set it to my own email address.

**Comment by staringispolite** [comment]
Ok, so I've already got values filled for all the Stripe and AWS .env vars, so I think we can rule that out. Running "grunt run" does create an event.json, but it looks like it's not creating it properly: I gather from other issues there should be a "source" value, and possible others?

![image](https://user-images.githubusercontent.com/151620/32386405-5458400e-c07e-11e7-8aa2-d6a41e348abe.png)

(note: my email is correctly in there, just didn't want to post it here)

**Comment by staringispolite** [comment]
Looking at the event.json creation code, it looks like it’s writing the
file with no key/value pair for source. Not even something like

“source”:””

Did some debugging, and the value of "token" in the callback function that writes event.json is undefined. Any idea why that would be?

**Comment by TaylorBriggs** [comment]
`token` should be returned by the call to `stripe.tokens.create`. Are you receiving an error in that callback function? I wonder if there's maybe something strange going on with Stripe API versions.

**Comment by staringispolite** [comment]
*”grunt run”

**Comment by staringispolite** [comment]
I did recently update to the latest Stripe API version... My account is
running 2017-08-15. Is that supported?

In the meantime, I’ll investigate what’s happening in stripe.tokens.create.
I’m not seeing any errors in the output from “grunt run” but maybe
they’re suppressed.

**Comment by TaylorBriggs** [comment]
According to [the docs](https://stripe.com/docs/api/node#versioning) the dashboard API version is used by default. This function was originally tested against API version `2016-06-15`, which is outdated. You can try running against that API version and see if you get different results. In the meantime, I'll try testing against the latest version to see if I can reproduce this bug.

**Comment by staringispolite** [comment]
Whoops, missed your earlier question. I'm not getting any errors, the token just returns `undefined`.

It looks like Stripe won't let me roll back to a specific API version, only the latest, or the (extremely old) version it was on before. If you know how, happy to test that for you.

**Comment by staringispolite** [comment]
Aha! I may have figured it out.
a) The callback function wasn't showing Stripe errors to the user in the token creation step. ([Made a PR to fix this if that's helpful](https://github.com/TaylorBriggs/stripe-lambda/pull/10))
b) Once I fixed that, I saw `Error: Your card was declined. Your request was in live mode, but used a known test card.` I had my live key in the .env, but the code runs a test card. Switched it to the test API key secret and it worked, and now I have a event.json with a `source`. Is this how it's supposed to work, and I just swap in the live key before pushing to Lambda? Or is it indicative of a misconfigured Stripe?

**Comment by staringispolite** [comment]
Update: got it working! In case future people run into issues here, the main things I needed to change were...
* Edit index.js to work with POST, and to work with Stripe Checkout
* Deploy with `grunt deploy --force` to ignore warnings (like how on live keys, the test card fails and it won't upload to Lambda)
* The edit above to see Stripe errors

**Comment by TaylorBriggs** [comment]
Very cool, thanks for the info! I have an idea for how to configure grunt to run with a test key and have the handler use the production key.

**Comment by TaylorBriggs** [comment]
@staringispolite #11 should give you a way to use the grunt tasks with the test key running in `build_event` and the live key used in the lambda function handler. Let me know what you think.

I'm planning to open another PR to update the function signature to match the newer node runtimes.

**Comment by TaylorBriggs** [comment]
@staringispolite This should be fixed with https://github.com/TaylorBriggs/stripe-lambda/commit/01dafbf7b15a45630aa77925106468cce7f65518. Let me know if you're still having issues!

**Comment by staringispolite** [comment]
Great, thanks for the update!
